global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bettercarehospitalapi-dev'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'bettercarehospitalapi-prod'
    static_configs:
      - targets: ['host.docker.internal:4000']
